 include /home/ryanku/Makefile

#		c makefile
#
#		ryan keleti

#SRCS:=$(wildcard *.c)
#OBJS:=${SRCS:.c=.o}
#NAME:=$(patsubst %.c,%,$(SRCS))

#INCLUDE_DIR:=
#LIBRARY_DIR:=
#LIBS:=

#LDFLAGS +=$(foreach libdir,$(LIBRARY_DIR),-L$(libdir))
#LDFLAGS +=$(foreach lib,$(LIBS),-l$(lib))
#CFLAGS:=-lm 

#.PHONY: all clean distclean remove

#all: $(OBJS)	

#$(OBJS): %.o: %.c
#	cc $< -o $@ $(CFLAGS)

#clean: 
#	@- $(RM) $(NAME)
#	@- $(RM) $(OBJS)

#distclean: clean

#remove:
#	rm -i `find . -perm /111 -type f`

